### ISSUE TITLE
Project will not compile

### ISSUE THREAD

**Issue by ghost** [peeveeone/ZLL_Multi_Endpoint_Dimmable_Light#1]
Hi, just wondering if the latest available source should be able to compile or if it is a local problem. The software and SDK plugin were installed as described on peeveeone.com.

The compiler errors out on "'zps_msgMcpsDcfm' could not be resolved zps_gen.c /ZLL_Multi_Endpoint_Dimmable_Light/Light_DimmableLight/Source line 799 Semantic Error"

![nxp](https://user-images.githubusercontent.com/16718229/28887847-ed1ba47e-77be-11e7-8396-27eeaa3d7ca7.png)

**Comment by lucacri** [comment]
Same issue for me, tried everything I could think of but getting the same error

**Comment by obelix05** [comment]
same issue for me, is there any solution for that?

**Comment by peeveeone** [comment]
This project is an incomplete work in progress I haven't updated for some time.  I will replace this project once I complete the  multi endpoint lights.
